# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.1-ce

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-npm-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-npm-dependencies

      - restore_cache:
          keys:
          - v1-elm-dependencies-{{ checksum "elm-package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-elm-dependencies

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-npm-dependencies-{{ checksum "package.json" }}

      - run: ./node_modules/.bin/elm-package install -y

      - save_cache:
          paths:
            - elm-stuff
          key: v1-elm-dependencies-{{ checksum "elm-package.json" }}

      - run: yarn run build
      - run: docker build -t vynlar/adrian_web:${CIRCLE_SHA1} .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push vynlar/adrian_web:$CIRCLE_SHA1

      - add_ssh_keys
      - deploy:
          name: Deploy adrian_web to docker-master-1
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -oStrictHostKeyChecking=no root@163.172.164.113 "docker stop adrian_web"
              ssh -oStrictHostKeyChecking=no root@163.172.164.113 " docker run -d --rm --name adrian_web -p 80:80 vynlar/adrian_web:${CIRCLE_SHA1}"
            fi
