# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "package.json" }}
          - elm-dependencies-{{ checksum "elm-package.json" }}
          # fallback to using the latest cache if no exact match is found
          - npm-dependencies-

      - run: yarn install


      - run: yarn run build
      - run: docker build -t vynlar/adrian_web:${CIRCLE_SHA1} .
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push vynlar/adrian_web:$CIRCLE_SHA1

      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - elm-stuff
          key: elm-dependencies-{{ checksum "elm-package.json" }}
